### PR TITLE
Update to 0.0.7-preview and demonstration of the error callback

### PR DESCRIPTION
**Pull request by SeanFeldman**
Addresses https://github.com/Azure/azure-service-bus-dotnet/issues/229

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@Azure/azure-service-bus-write please review

**Comment by nemakam** [comment]
@SeanFeldman , thanks for this PR.

**Comment by SeanFeldman** [comment]
@nemakam you're welcome.
BTW, you can delete the branch used for PR once PR is merged
(@vinaysurya already knows about it 🙂)

**Comment by nemakam** [comment]
@SeanFeldman  Don't think we have permission to delete the branch in your repo. We do try to delete the branches that we opened.

**Comment by SeanFeldman** [comment]
Ah, it's on the new client repo where we're collaborators. My bad 😃

**Pull request merged**
